version: '3'

services:
  srs:
    image: daocloud.io/shaobo_wu/srs-docker:latest
    command: /tmp/srs/gen_conf_and_run.sh
    ports:
      - "21935:1935"
      - "20080:80"
    environment:
      - config.env
